FROM node:18-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build   # build কমান্ড চালাও

FROM node:18-alpine
RUN npm install -g serve
WORKDIR /app
COPY --from=builder /app/build ./build  # এটা build ফোল্ডার কপি করবে

EXPOSE 80
CMD ["serve", "-s", "build", "-l", "80"]
